PedroDCA/disenoweb

package-lock.json, package.json, src/dataAccess/userDataAccess.js, src/database/firebase.js, src/index.js, src/service/userService.js
Hi!
Here I am setting the configuration for firebase database.
Also, creating the first service and data access for adding a new user.
Thanks
=> Setting the firebase configuration

src/App.js, src/components/header.js, src/components/homepage.js, src/components/logoSection.js, src/components/productDetail.js, src/components/searchPage.js, src/components/signPage.js, src/store/actions.js, src/store/reducers.js, src/styles/header.css
Hi!
Here I am setting the base to be able to have access to the Cart State. Which means we can access to the information that is on the cart on any page, so I already added a badge on the cart logo to show when there is any product on the cart with the number of different items on there.
For this, I already added two different actions to be able to manage the adding and the removing of the items on the cart. In this way, we only have to trigger the dispatch with the action we want, and the reducer will be in charge to execute every step it should, in this way we keep the logic just on one part and make the other agnostic.
Also, adjusting a bit the formatting on some files.
Thanks
=> Setting the base for the Cart State

src/service/priceService.js
Hi team!
Here I am adding a comment for the format function
Thanks
=> Commenting the format function

package-lock.json, package.json, src/App.js, src/components/homepage.js, src/components/logoSection.js, src/components/productCard.js, src/components/productDetail.js, src/components/productDetailPage.js, src/components/productList.js, src/components/searchPage.js, src/components/signPage.js, src/service/productService.js, src/store/reducers.js
Hi!
Here I am setting the information without css for the detail pages to according to the item.
I adjusted some services to be able to reuse the mock data.
I set the information and HTML required for the detail pages.
Also, fixing a issue related to the cart when changing to sign page.
Thanks
=> Adding information to detail page

src/components/homepage.js, src/components/signPage.js, src/styles/logoSection.css, src/styles/signPage.css
Hi, I just changed the signup and sign-in with the colors and sizes we are using for the project as well as images. Also created filters for the homepage with their links to the search
=> CSS for home and Sign in and Sign up

src/App.js, src/components/header.js, src/components/paymentItem.js, src/components/paymentItemList.js, src/components/paymentPage.js, src/components/paymentTotalSection.js, src/components/productCard.js, src/components/productDetail.js, src/service/priceService.js, src/store/actions.js
Hi team!
Here I am almost all the payment page for the items the user has on the cart.
Where you can see the list of items, its cost per item, quantity and total per item.
It is missing the total resume and also I have to implement redux here. It will help much to manage states as currently we are going to have the cart state and a total prices state
=> Adding payment page

src/components/paymentPage.js, src/components/paymentTotalSection.js
Hi!
Here I am adding the payment total section on the payment page.
=> Adding payment total section

src/components/paymentItem.js, src/components/paymentItemList.js, src/components/paymentTotalSection.js, src/styles/paymentItem.css, src/styles/paymentItemList.css, src/styles/paymentTotalSection.css
=> Payment PageCSS

src/App.js, src/components/cartModal.js, src/components/header.js, src/components/profileInformationSection.js, src/components/profilePage.js, src/components/userOrder.js, src/components/userOrderHistorySection.js, src/service/dateService.js, src/store/cart/index.js, src/store/index.js, src/store/user/index.js
Hi team!
Here I am adding the user profile page. It includes the User Panel, where the user updates its information, and the User Order History, where the user can see all its order.
It does not include the styles.
Thanks
=> Adding user profile page

src/components/header.js, src/components/profileInformationSection.js, src/components/profilePage.js, src/components/vendorOrderHistorySection.js, src/components/vendorProduct.js, src/components/vendorProductList.js, src/service/profileService.js, src/store/index.js, src/store/profile/index.js
Hi team!
Here I am adding the Vendor Profile section, where you can see the Vendor Panel, the Product List and the Vendor Orders
Thanks
=> Adding Vendor Profile Section

src/components/footer.js, src/components/productDetail.js, src/components/productDetailPage.js, src/components/searchPage.js, src/dataAccess/productDataAccess.js, src/dataAccess/productRatingsDataAccess.js, src/dataAccess/userDataAccess.js, src/dataAccess/vendorDataAcess.js, src/dataAccess/vendorRatingsDataAccess.js, src/service/productService.js, src/service/userService.js, src/service/vendorService.js, src/utils/caseConverter.js
Added DataAccess for product, productRatings, vendor, vendorRatings and CRUD functions. Added product services and its functions. Added vendor service and a function to get vendors ratings.
=> Add DataAccesses and Services

src/components/profilePage.js, src/components/userOrder.js, src/dataAccess/productDataAccess.js, src/service/productService.js, src/service/profileService.js
Hi team!
Here I am adding the functionality for the user order, where you can get the user order according to the user.
Thanks
=> Adding the user order functions

src/dataAccess/paymentDataAccess.js, src/dataAccess/productDataAccess.js, src/dataAccess/receiptDataAccess.js, src/service/paymentService.js
Hi team!
Here I am adding the processes to the payment.
Thanks
=> Adding payment process

src/App.js, src/components/checkoutItem.js, src/components/checkoutPage.js, src/components/paymentPage.js, src/components/profilePage.js, src/components/userOrder.js, src/dataAccess/productDataAccess.js, src/dataAccess/receiptDataAccess.js, src/dataAccess/userDataAccess.js, src/service/paymentService.js, src/service/productService.js, src/service/profileService.js, src/store/cart/index.js, src/store/index.js
Hi team!
Here I am adding some payment backend process and also some adjusts on the user order list
Thanks
=> Payment backend process

src/components/vendorOrderHistorySection.js, src/dataAccess/productDataAccess.js, src/service/paymentService.js, src/service/productService.js, src/service/profileService.js, src/store/cart/index.js
Hi team!
Here I am adding the backend logic to be able to fetch the vendor order history on the profile section.
Thanks
=> Showing the vendor order history with database information

src/components/profileInformationSection.js, src/components/signPage.js, src/dataAccess/userDataAccess.js, src/dataAccess/vendorDataAcess.js, src/database/firebase.js, src/service/signingService.js, src/service/userService.js, src/service/vendorService.js, src/styles/signPage.css
Hi team!
Here I am finishing the signing process, where the users and vendor can create and sign in its accounts
Thanks
=> Finishing the signing process

package-lock.json, package.json, src/components/newProductForm.js, src/components/productDetail.js, src/components/vendorProductList.js, src/service/imageService.js, src/service/productService.js
Hi team!
Here I am adding the functionality to be able to add a new product for the vendor on the profile page.
Thanks
=> Adding add a new product functionality

package-lock.json, package.json, src/components/signPage.js, src/styles/signPage.css
Fixed radio button on signin and login
=> Fixed radio button

src/components/vendorOrderHistorySection.js, src/dataAccess/receiptDataAccess.js, src/service/orderService.js
Hi team!
Here I am adding the process to update the order status
=> Updating order status 

src/components/productDetail.js, src/components/userOrder.js, src/dataAccess/productDataAccess.js, src/dataAccess/productRatingsDataAccess.js, src/dataAccess/vendorRatingsDataAccess.js, src/service/productService.js, src/service/ratingService.js, src/service/vendorService.js
Hi team!
Here I am adding the process to add a new rating for products and vendor when a user buys a product.
Thanks
=> Adding the rating process for products and vendors

src/components/logoSection.js, src/components/vendorProduct.js, src/components/vendorProductList.js, src/dataAccess/productDataAccess.js, src/dataAccess/userDataAccess.js, src/service/productService.js
Hi team!
Here I am fixing some issues I noticed on our today's call
Thanks
=> Fixing issues

src/components/productDetail.js, src/service/productService.js
Hi team!
Here I am adding some changes on content
Thanks
=> Adding final fixes
